version: "3.7"

services:
  postgres:
    container_name: 'junior-club-postgres'
    image: 'postgres:14.5'
    restart: always
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_DB=junior_club_postgres'
      - 'POSTGRES_PASSWORD=admin'
    expose:
      - 5432
  backend:
    container_name: 'junior-club-backend'
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    expose:
      - 8000
  frontend:
    container_name: 'junior-club-frontend'
    restart: always
    build: ./frontend
    ports:
        - "3000:3000"



