version: "3.7"

services:

  postgres:
    container_name: 'postgres_dev'
    image: 'postgres:14.5'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_DB=postgres_dev'
      - 'POSTGRES_PASSWORD=admin'